### ISSUE TITLE
Save old appearance when disconnecting with mask

### ISSUE THREAD

**Issue by lexinor** [FuTTiiZ/mask-fix#2]
I tried testing your script and it was almost perfect but after disconnecting with my mask on, when reconnecting and removing the mask, I was complety bold since the appearance is not saved.

Any idea where in the script we can implement the "save" part ?

**Comment by FuTTiiZ** [comment]
Sure. I actually originally wrote the script using client-side KVPs (key-value pairs).

Saving this stuff is kinda tricky when doing it standalone. I deliberately didn't want to add extra server-sided SQL dependencies. Any server running common frameworks already have their own ways of storing your appearance anyways. I suggest you look into your preferred framework's way of getting saved facial data and use that instead of the `savedBlendData` local variable. The best way of using this script is in my opinion to fork it and tailor it to your own server's needs.

With that said, you could easily save the player's head blend data to the client's PC with client-side KVPs (key-value pairs). This has some downsides, and in my opinion you shouldn't really save that kind of data on the client. Here's an excellent video explaining FiveM KVPs: https://www.youtube.com/watch?v=LNR9m2zciPE
<br/>
To implement it, however, you could essentially just change the following lines:
<br/>
Load last saved data
https://github.com/FuTTiiZ/mask-fix/blob/e066edacd599f74c067122839bbc1bc1836ffd49/client.lua#L50
```lua
local savedBlendData = json.decode(GetResourceKvpString('sBlendData')) or {}
local savedFaceFeatures = json.decode(GetResourceKvpString('sFaceFeatures')) or {}
```
<br/>

Save head blend data
https://github.com/FuTTiiZ/mask-fix/blob/e066edacd599f74c067122839bbc1bc1836ffd49/client.lua#L91

```lua
savedBlendData = headBlendData
SetResourceKvp('sBlendData', json.encode(savedBlendData))
```
<br/>

Save facial features
https://github.com/FuTTiiZ/mask-fix/blob/e066edacd599f74c067122839bbc1bc1836ffd49/client.lua#L101-L104
```lua
for i = 0, 19 do 
   savedFaceFeatures[i] = GetPedFaceFeature(ped, i) 
   SetPedFaceFeature(ped, i, 0.0) 
end 
SetResourceKvp('sFaceFeatures', json.encode(savedFaceFeatures))
```


<br/>
Hope this helps :)

**Comment by lexinor** [comment]
Well, thanks for your precise answer !
I will try to implement that and I might come back for more infos :D !

A last question, I'm having issues hiding hairs even when setting the correct height (-0.5) in YMT files, it seems to have no effect. (I'm using Durty Cloth Tool)
Do you think I could use this script to handle hair stuff ?

**Comment by FuTTiiZ** [comment]
You could rewrite the script to also fix certain hair issue.
Most issues with hair, however, stem from item who've been given improper flags by their devs.
